# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Thu Feb 17 12:50:40 2022)---
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Thu Feb 17 16:07:30 2022)---
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Fri Feb 18 11:25:36 2022)---
album =
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
crear_album(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
crear_album(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
crear_album(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
crear_album(6)
crear_album(8)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(5, 5)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(5, 5)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(5, 5)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(5, 5)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(5, 3)
experimentar(3, 3)
experimentar(2, 2)
experimentar(2, 3)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(2, 3)
experimentar(2, 2)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(2, 2)
experimentar(2, 3)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(2, 3)
experimentar(2, 2)

## ---(Sat Feb 19 11:54:05 2022)---
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
comprar_paquete(5,2)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
comprar_paquete(5,2)
crear_album(7)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
crear_album(7)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
hay_alguno(5,2)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
hay_alguno(5,2)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
comprar_paquete (6 , 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(6)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10, 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10, 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10, 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(10, 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
comprar_paquete(10, 5)
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
comprar_paquete(10, 5)
crer_album(8)
crear_album(8)
hay_alguno([0,0,0,0],[1,2,3,4])
hay_alguno([0,0,0,0],[1,2,3,0])
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
hay_alguno([1,2,3,4],[1,2,3,0])
hay_alguno([1,2,3,4],[1,2,3,4])
hay_alguno([1,2,3,4],[1,0,3,4])
hay_alguno([1,2,3,4],[1,0,0,4])

## ---(Sun Feb 20 12:10:45 2022)---
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(10, 5)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(10, 5)
experimentar(10, 100)
experimentar(10, 1000)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
experimentar(10, 1000)
experimentar(10, 10000)
experimentar(10, 100000)

## ---(Sun Feb 20 12:47:12 2022)---
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(6)
runfile('C:/Users/orteg/Desktop/untitled0.py', wdir='C:/Users/orteg/Desktop')
cuantas_figus(6)
hay_alguno([0,0,0,0,1,0],[1,0])
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
hay_alguno([0,0,0,0,1,0],[1,0])
hay_alguno([0,0,0,0,1,0],[0,1])
hay_alguno([0,0,0,0,1,0],[0,0])
hay_alguno([0,0,0,0,1,0],[2,4])
hay_alguno([0,0,0,0,1,0],[2,1])
runfile('C:/Users/orteg/Desktop/GUTIII.py', wdir='C:/Users/orteg/Desktop')
def album_lleno(l):
    lleno = False
    for i in range (0, len(l),1):
        if l[i] == 1:
            lleno = True

## ---(Tue Feb 22 01:34:57 2022)---
runfile('C:/Users/orteg/Desktop/kpo.py', wdir='C:/Users/orteg/Desktop')

## ---(Tue Feb 22 14:18:05 2022)---
runfile('C:/Users/orteg/Desktop/Phyton/kpo.py', wdir='C:/Users/orteg/Desktop/Phyton')
estimacion_juan_gana(3, 5, 0.5, 1000)
runfile('C:/Users/orteg/Desktop/Phyton/kpo.py', wdir='C:/Users/orteg/Desktop/Phyton')
estimacion_juan_gana(3, 5, 0.5, 1000)
runfile('C:/Users/orteg/Desktop/Phyton/kpo.py', wdir='C:/Users/orteg/Desktop/Phyton')
estimacion_juan_gana(3, 5, 0.5, 1000)
runfile('C:/Users/orteg/Desktop/Phyton/kpo.py', wdir='C:/Users/orteg/Desktop/Phyton')

## ---(Thu Feb 24 14:29:06 2022)---
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Tue Mar  1 13:43:35 2022)---
runfile('C:/Users/orteg/untitled0.py', wdir='C:/Users/orteg')

## ---(Tue Mar  1 18:39:09 2022)---
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar  7 18:41:45 2022)---
generar_poblacion(8)
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
generar_poblacion(8)
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
generar_poblacion(8)
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
distribuir(9,8)
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
distribuir(9,8)
runfile('C:/Users/orteg/.spyder-py3/temp.py', wdir='C:/Users/orteg/.spyder-py3')
distribuir(9,8)
generar_mazo(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazo(4)
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
generar_mazos(4)
generar_mazos()
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())
runfile('C:/Users/orteg/.spyder-py3/halcones.py', wdir='C:/Users/orteg/.spyder-py3')
jugar(generar_mazos())

## ---(Tue Mar  8 10:30:19 2022)---
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
jugar_varios(generar_mazos(),2)
jugar_varios(generar_mazos(),5)
jugar_varios(generar_mazos(),2)
jugar_varios(generar_mazos(),5)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
jugar_varios(generar_mazos(),5)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
jugar_varios(generar_mazos(),5)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Wed Mar  9 17:38:37 2022)---
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Thu Mar 10 16:06:51 2022)---
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
par(7)
par(8)
par(2)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
par(2)
par(7)
par(8)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
collatz(random.randint(1,100))
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
collatz(random.randint(1,100))
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
collatz(random.randint(1,100))
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
collatz(random.randint(1,100))
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
len_collatz(random.randint(1,100))
len_collatz(random.randint(1,1000))
len_collatz(random.randint(1,10000))
collatz(random.randint(1,100))
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
collatz(3)
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nanoblack.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Fri Mar 11 19:30:10 2022)---
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
multiplo(2,8)
multiplo(8, 2)
multiplo(8, 8)
multiplo(8, 10)
multiplo(8, 4)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(8)
primo(9)
primo(10)
primo(11)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(11)
primo(10)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(10)
primo(11)
primo(7)
primo(8)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(7)
primo(121)
primo(123)
primo(1069)
primo(1)
primo(2)
primo(3)
primo(4)
primo(5)
primo(6)
primo(7)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(7)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factorizar(60,2)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factorizar(60,2)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factorizar(60,2)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(4)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(4)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(4)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(4)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(4)
factores_primos(9)
factores_primos(90)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factorizar(9,3)
factorizar(9,4)
factorizar(18,3)
factorizar(18,2)
factorizar(20,2)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
factores_primos(60)
factores_primos(405)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(405)
factores_primos(15)
factores_primos(60)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(60)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(60)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(60)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(60)
factores_primos(2378)
factores_primos(1678)
factores_primos(1638)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(1638)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(1638)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(1638)
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
factores(15)
factores(10)
factores(20)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(20)
factores_primos(15)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(15)
factores_primos(30)
factores_primos(50)
factores(50)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores(50)
factores_primos(50)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(50)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(50)
factores_primos(21)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(1638)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factpres_primos(4001)
factores_primos(4001)
factores_primos(20)
factores_primos(27)
factores_primos(41)
factores_primos(50)
factores_primos(4002)
factores_primos(190)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(409)
primo(419)
primo(410)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
primo(423)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
factores_primos(423)
runfile('C:/Users/orteg/.spyder-py3/proyectoEuler.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,3)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,3)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,3)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,3)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,3)
campo_minado(6,8,19)
campo_minado(6,8,35)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,7)
campo_minado(6,8,15)
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(6,8,15)
campo_minado(6,8,25)
campo_minado(6,8,47)
runcell(0, 'C:/Users/orteg/.spyder-py3/untitled0.py')
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Sat Mar 12 01:25:42 2022)---
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Sat Mar 12 16:32:45 2022)---
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
campo_minado(8,9,7)
campo_minado(8,9,71)
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
3
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
pedir_c
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
pedir_c
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
1
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
1
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Sun Mar 13 15:22:10 2022)---
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runcell(1, 'C:/Users/orteg/.spyder-py3/nashe22.py')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/nashe22.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar 14 01:45:30 2022)---
runfile('C:/Users/orteg/.spyder-py3/untitled0.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar 14 03:20:24 2022)---
a=2
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar 14 15:59:41 2022)---
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runcell(0, 'C:/Users/orteg/.spyder-py3/mastermind.py')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar 14 17:08:56 2022)---
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom(4)
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom()
listarandom(4)
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom(4)
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
listarandom(4)
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Mon Mar 14 19:58:15 2022)---
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/mastermind.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Wed Mar 16 15:44:16 2022)---
runfile('C:/Users/orteg/.spyder-py3/orbitas.py', wdir='C:/Users/orteg/.spyder-py3')
mano(7)
runfile('C:/Users/orteg/.spyder-py3/orbitas.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Wed Mar 16 19:10:28 2022)---
runfile('C:/Users/orteg/.spyder-py3/scrabble.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/scrabble.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/scrabble.py', wdir='C:/Users/orteg/.spyder-py3')
a=3
a=3
runfile('C:/Users/orteg/.spyder-py3/scrabble.py', wdir='C:/Users/orteg/.spyder-py3')
runfile('C:/Users/orteg/.spyder-py3/scrabble.py', wdir='C:/Users/orteg/.spyder-py3')

## ---(Wed Mar 16 21:30:20 2022)---
runfile('C:/Users/orteg/.spyder-py3/visualizacion.py', wdir='C:/Users/orteg/.spyder-py3')